(define (domain sap_intersection-domain)
 (:requirements :strips :typing :durative-actions)
 (:types loc direction)
 (:predicates (connected ?l1 - loc ?l2 - loc ?d - direction) (free ?l - loc) (at_ ?l1 - loc) (arrived) (not_arrived) (start_ ?l - loc) (traveldirection ?d - direction))
 (:durative-action arrive
  :parameters ( ?l - loc)
  :duration (= ?duration 1)
  :condition (and (at start (start_ ?l))(at start (not_arrived))(over all (free ?l)))
  :effect (and (at end (at_ ?l)) (at end (not (free ?l))) (at end (arrived)) (at end (not (not_arrived)))))
 (:durative-action drive
  :parameters ( ?l1 - loc ?l2 - loc ?d - direction)
  :duration (= ?duration 1)
  :condition (and (at start (at_ ?l1))(at start (traveldirection ?d))(at end (connected ?l1 ?l2 ?d)))
  :effect (and (at end (at_ ?l2)) (at end (not (free ?l2))) (at end (free ?l1)) (at start (not (at_ ?l1)))))
)
